
version: 0.2

env:
  secrets-manager:
    SECRETS: SECRETS

phases:
  pre_build:
    commands:
        - echo Logging in to Amazon ECR...
        - echo ${SECRETS}
        - export AWS_ACCOUNT_ID=$(echo $SECRETS | jq -r '.AWS_ACCOUNT_ID')
        - export AWS_DEFAULT_REGION=$(echo $SECRETS | jq -r '.AWS_DEFAULT_REGION')
        - export IMAGE_REPO_NAME=$(echo $SECRETS | jq -r '.IMAGE_REPO_NAME')
        - export IMAGE_TAG=$(echo $SECRETS | jq -r '.IMAGE_TAG')
        - echo "AWS_ACCOUNT_ID:$AWS_ACCOUNT_ID"
        - echo "AWS_DEFAULT_REGION:$AWS_DEFAULT_REGION"
        - echo "IMAGE_REPO_NAME:$IMAGE_REPO_NAME"
        - echo "IMAGE_TAG:$IMAGE_TAG"
        - docker login -u AWS -p $(aws ecr get-login-password) https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

  build:
    commands:
        - echo Build started on `date`
        - echo Building the Docker image...          
        - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
        - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
